name: sistema_contable
description: Sistema contable web
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.0
  sqflite: ^2.4.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0  # Agregado para formateo de fechas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true